platformName : Android

# 夜神模拟器
platformVersion : 4.4.2
deviceName : 127.0.0.1:62001

# 逍遥模拟器
#platformVersion : 5.1.1
#deviceName : 127.0.0.1:21503

# 真机红米4
#platformVersion : 5.1.1
#udid : 750BBKL22GDN
#deviceName : MX4

appname : mixpace-dev-v1.8.0-official.apk
appPackage : com.mixpace.android.mixpace
appActivity : com.mixpace.android.mixpace.activity.WelcomeActivity

noReset : False
unicodeKeyboard : True
resetKeyboard : True

ip : 127.0.0.1
port : 4723

